"""metas_completas

Revision ID: 37c28aa4607b
Revises: 8cd6e5dfa832
Create Date: 2026-05-22 21:40:16.416450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37c28aa4607b'
down_revision = '8cd6e5dfa832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
